- job:
    name: test_job
    description: 'job description'
    project-type: freestyle
    parameters:
    - string:
          name: my_var_file
          default: 'https://raw.githubusercontent.com/hongkailiu/svt-case-doc/master/files/terraform/ocp_var/var_file_all_in_one.tfvars'
    - string:
          name: static_ocp_inventory
          default: 'https://raw.githubusercontent.com/hongkailiu/test-go/master/test_files/ocpft/inv/2.file'
    builders:
    - shell: |
        rm -rfv ./svt-case-doc
        git clone https://github.com/hongkailiu/svt-case-doc.git
        ./svt-case-doc/scripts/tf_flexy_jenkins.sh